# netlify.toml

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://relaxed-mochi-7581fa.netlify.app, https://mfe-tutorial.vercel.app/"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE"
    Access-Control-Allow-Headers = "Content-Type"

# _redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
